/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "torchpipe",
  "tagline": "torchpipe wants to bridge the gap between deep learning training and ensemble pipeline deployment.",
  "url": "https://torchpipe.github.io",
  "baseUrl": "/zh/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "images/logo_double.svg",
  "organizationName": "torchpipe",
  "projectName": "tp.github.io",
  "deploymentBranch": "master",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "zh",
      "en"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr"
      },
      "zh": {
        "label": "简体中文",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/docs",
          "sidebarPath": "/workspace/website/sidebars.js",
          "sidebarCollapsed": true,
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "theme": {
          "customCss": [
            "/workspace/website/src/css/custom.css",
            "/workspace/website/src/css/helpers.css",
            "/workspace/website/src/css/auto-number-title.css"
          ]
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        },
        "gtag": {
          "trackingID": "G-1LKTTC3R7Q",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {}
    },
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "deploy, pytorch, serving, pipeline parallelism, torchpipe"
      },
      {
        "name": "description",
        "content": "serving inside pytorch with multiple threads."
      },
      {
        "name": "og:image",
        "content": "__.png"
      }
    ],
    "navbar": {
      "title": "torchpipe",
      "logo": {
        "alt": "torchpipe Logo",
        "src": "images/logo.svg",
        "srcDark": "images/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "welcome",
          "position": "left",
          "label": "文档 "
        },
        {
          "type": "docSidebar",
          "sidebarId": "api",
          "position": "left",
          "label": "API"
        },
        {
          "type": "doc",
          "position": "left",
          "label": "案例展示",
          "docId": "showcase/showcase"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://g.hz.netease.com/deploy/torchpipe/-/tree/master",
          "className": "header-gitlab-link",
          "aria-label": "GitLab repository",
          "position": "right",
          "title": "torchpipe on Gitlab"
        }
      ],
      "hideOnScroll": true
    },
    "footer": {
      "copyright": "© 2023 nisp. All rights reserved <br /> this page is modified from <a href='https://lerna.js.org/'>lerna</a> and built with <a href='https://docusaurus.io/'>docusaurus</a>. ",
      "style": "light",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "toml",
        "ini"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "themes": [
    [
      "/workspace/website/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en",
          "zh"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true,
        "searchResultLimits": 12,
        "searchBarPosition": "auto"
      }
    ],
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
